
-- Skills -refernced from https://enhancv.com/resume-skills/#design

insert into tags (name)
values
('Ms Excel'),
('Photoshop'),
('CAD'),
('Adobe'),
('Revit'),
('Maya'),
('Videography'),
('Design'),
('Visual Art'),
('Mentoring'),
('Client Relations'),
('Stakeholder Management'),
('Training'),
('Team Management'),
('People Management'),
('Powerpoint'),
('Lean'),
('Compliance'),
('Evaluation'),
('Reporting'),
('VBA'),
('Procurement'),
('Contract Management'),
('Scheduling'),
('Implementation'),
('Fundraising'),
('Sustainability'),
('Client Management'),
('Crisis Management'),
('Manufacturing'),
('Performance Management'),
('BPM'),
('SAP'),
('Purchasing'),
('Quality Management'),
('Microsoft Project'),
('Logistics'),
('Event Management'),
('Report Writing'),
('Relationship Management'),
('Risk Management'),
('Automotive'),
('Lean Six Sigma'),
('Process Improvement'),
('Insurance'),
('Quality Assurance'),
('faciliation'),
('Vendor Management'),
('Planning'),
('Financial Modeling'),
('Asset Management'),
('Management'),
('Business'),
('Budget Management'),
('Billing'),
('Payroll'),
('Budgeting'),
('Forecasting'),
('Finance'),
('Accounting'),
('Robotics'),
('Automation'),
('Hardware'),
('Engineering'),
('Python'),
('Java'),
('Javascript'),
('Git'),
('SQL'),
('HTML'),
('MySQL'),
('CSS'),
('Autocad'),
('AWS'),
('Matlab'),
('Jira'),
('Linux'),
('Docker'),
('Jenkins'),
('C'),
('C#'),
('PHP'),
('Mongodb'),
('Bootstrap'),
('Agile'),
('jQuery'),
('Problem solving'),
('Angular'),
('Typescript'),
('Wordpress'),
('Ecommerce'),
('CMS'),
('Lead Generation'),
('Facebook'),
('Content Management'),
('Storytelling'),
('Marketing'),
('Telecommunications'),
('Trading'),
('Sales'),
('Active Directory'),
('Blockchain'),
('Database Management'),
('Cloud'),
('Internet'),
('Oracle'),
('C++'),
('SQL Server'),
('OOP'),
('Scripting'),
('React'),
('Statistics'),
('Data Management'),
('CCNA'),
('Penetration Testing'),
('IBM'),
('Data Warehouse'),
('Technical Support'),
('Mathematics'),
('Unix'),
('Machine Learning'),
('ETL'),
('AS400'),
('IoT'),
('Integration'),
('Artificial Intelligence'),
('Testing'),
('Software Testing'),
('Data Modelling'),
('Data Collection'),
('Data Center'),
('SPSS'),
('Mainframe'),
('Hadoop'),
('Statistical Analysis'),
('GIS'),
('Spark'),
('c++'),
('bpm'),
('ccna'),
('cms'),
('data management'),
('css'),
('data collection'),
('data center'),
('artificial intelligence'),
('scripting'),
('sql server'),
('iot'),
('data modelling'),
('machine learning'),
('spark'),
('vba'),
('hadoop'),
('microsoft access'),
('statistics'),
('wordpress'),
('penetration testing'),
('mainframe'),
('oop'),
('software testing'),
('gis'),
('spss'),
('microsoft office'),
('data warehouse'),
('react'),
('statistical analysis'),
('unix'),
('etl'),
('as400'),
('MS Excel'),
('Microsoft Access'),
('Microsoft Word'),
('Microsoft Office'),
('Computer'),
('Documentation'),
('Administrative'),
('Office'),
('Cooking'),
('Food Service'),
('Work Under Pressure'),
('Flexibility'),
('Independent'),
('Analytical Thinking'),
('Collaborative'),
('Strong Work Ethic'),
('Decision Making'),
('Motivation'),
('Critical Thinking'),
('Detail Oriented'),
('Organizational'),
('People'),
('Problem Solving'),
('Responsibility'),
('Interpersonal'),
('Team Leadership'),
('Teamwork'),
('Time Management'),
('Communication'),
('Innovation'),
('Coordinating'),
('Proactive'),
('Patience'),
('Reliability'),
('Multi-Tasking'),
('Persuasion'),
('Collaboration'),
('Creative Thinking'),
('Conceptual'),
('Strategic Thinking'),
('Negotiation'),
('Dealing with Ambiguity'),
('Emotional Intelligence'),
('Active Listening'),
('Transferable'),
('Fast Learner'),
('Public Speaking'),
('Conflict Resolution'),
('Resilience'),
('Willingness to Learn'),
('Networking'),
('Empathy'),
('Initative'),
('Closing'),
('Engagement'),
('Dealing with Objection'),
('Creating Good Rapport'),
('Confidence'),
('Diligence'),
('Initiative'),
('Patient Assessment'),
('Administering Injections'),
('Patient Care'),
('Phlebotomy'),
('Taking Vital Signs'),
('Contract Law'),
('Litigation'),
('Civil Litigation'),
('Legal Writing'),
('Legal Research'),
('Commercial Litigation'),
('Civil Law'),
('Criminal Law'),
('Dispute Management'),
('Cold Calling'),
('Oral Communication'),
('CRM Systems'),
('Salesforce'),
('Product Knowledge'),
('Technical Expertise'),
('Inventory Management'),
('Cleaning Equipment'),
('Packing'),
('Loading and Unloading Trucks'),
('Record-Keeping'),
('Shipping'),
('Lifting Heavy Items'),
('Warehouse'),
('Human Resource Management (HRM)'),
('Applicant Screening'),
('HR Strategy Creation'),
('Career Coaching'),
('HR Reporting'),
('Employee Relations'),
('Human Resources'),
('Lean Manufacturing'),
('Payment Processing'),
('Linear Regression'),
('Prototyping'),
('Technical'),
('Hotel Management and Operations'),
('Maintenance and Cleaning'),
('Staff Management'),
('Central Reservation System “CRS”'),
('Hospitality');



-- Queries For categories/subcategories:-


alter table categories auto_increment=0;

insert into categories (name)
values
('Accounting & Consulting'),
('Admin Support'),
('Customer Service'),
('Data Science & Analytics'),
('Design & Creative'),
('IT & Networking'),
('Legal'),
('Sales & Marketing'),
('Translation'),
('Web, Mobile & Software Dev'),
('Writing');


insert into subcategories (name,category_id)
values
('Accounting & Bookkeeping',1),
('Financial Planning',1),
('Management Consulting & Analysis',1),
('Personal & Professional Coaching',1),
('Recruiting & Human Resources',1),
('Other - Accounting & Consulting',1),
('Data Entry & Transcription Services',2),
('Market Research & Product Reviews',2),
('Project Management',2),
('Virtual Assistance',2),
('Community Management & Tagging',3),
('Customer Service & Tech Support',3),
('AI & Machine Learning',4),
('Data Analysis & Testing',4),
('Data Design & Visualization',4),
('Data Extraction/ETL',4),
('Data Mining & Management',4),
('Art & Illustration',5),
('Audio & Music Production',5),
('Branding & Logo Design',5),
('Graphic, Editorial & Presentation Design',5),
('NFT, AR/VR & Game Art',5),
('Performing Arts',5),
('Photography',5),
('Product Design',5),
('Video & Animation',5),
('3D Modeling & CAD',6),
('Building & Landscape Architecture',6),
('Chemical Engineering',6),
('Civil & Structural Engineering',6),
('Contract Manufacturing',6),
('Electrical & Electronic Engineering',6),
('Energy & Mechanical Engineering',6),
('Interior & Trade Show Design',6),
('Physical Sciences',6),
('Database Management & Administration',7),
('DevOps & Solution Architecture',7),
('ERP/CRM Software',7),
('Information Security & Compliance',7),
('Network & System Administration',7),
('Corporate & Contract Law',8),
('Finance & Tax Law',8),
('International & Immigration Law',8),
('Public Law',8),
('Digital Marketing',9),
('Lead Generation & Telemarketing',9),
('Marketing, PR & Brand Strategy',9),
('Language Tutoring & Interpretation',10),
('Translation & Localization Services',10),
('Blockchain, NFT & Cryptocurrency',11),
('Desktop Application Development',11),
('Ecommerce Development',11),
('Game Design & Development',11),
('Mobile Development',11),
('Product Management',11),
('QA Testing',11),
('Scripts & Utilities',11),
('Web & Mobile Design',11),
('Web Development',11),
('Other - Software Development',11);